services:
  client:
    build: ../client
    ports:
      - "80:80"
    depends_on:
      - server
    restart: always
    networks:
      - public

  server:
    build: ../server
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - redis
    restart: always
    networks:
      - public
      - private

  redis:
    image: redis:alpine
    expose:
      - "6379"
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - private

volumes:
  redis_data:

networks:
  public:
    driver: bridge
  private:
    driver: bridge
    internal: true
